Repository vertelab/odoo-mail, pull requests merged in 2020-12, with the labels that each got.

#2 [ADD] mail_oe_chatter_user_groups: adding module mail_oe_chatter_use…
  mail_oe_chatter_user_groups/__init__.py
  mail_oe_chatter_user_groups/__manifest__.py
  mail_oe_chatter_user_groups/models/__init__.py
  mail_oe_chatter_user_groups/models/hr_location.py
  mail_oe_chatter_user_groups/security/chatter_security.xml
  mail_oe_chatter_user_groups/static/description/icon.png
  mail_oe_chatter_user_groups/views/hr_location_views.xml
  mail_oe_chatter_user_groups/views/hr_views.xml
  mail_oe_chatter_user_groups/views/partner_view.xml
Labels: Prio 2

#3 [ADD] send_mail_nadim AFC-364: Add module
  send_mail_nadim/Flask_server/Flask_server.zip
  send_mail_nadim/Flask_server/Readme.pdf
  send_mail_nadim/__init__.py
  send_mail_nadim/__manifest__.py
  send_mail_nadim/models/__init__.py
  send_mail_nadim/models/ir_mail_server.py
  send_mail_nadim/security/ir.model.access.csv
  send_mail_nadim/views/out_going_server.xml
Labels: need install / smoke test

#4 [MOV] af_calender_reports: Copied from odoo-mail
  mail_calendar_report_crm/__init__.py
  mail_calendar_report_crm/__manifest__.py
  mail_calendar_report_crm/data/mail_template.xml
  mail_calendar_report_crm/models/__init__.py
  mail_calendar_report_crm/models/calendar_appointment.py
  mail_calendar_report_crm/views/appointment_report.xml
  mail_calendar_report_crm/views/calendar_appointment.xml
  mail_calendar_report_crm/views/updated_appointment_report.xml
Labels: Prio 1

#5 send_nadim_mail: AFC-364 improvments for sending mail
  send_mail_nadim/models/ir_mail_server.py
Labels: Prio 1

#6 12.0 afc-1139-mail-templates
  mail_outplacement_report/__manifest__.py
  mail_outplacement_report/data/auth_signup_custom_data.xml
  mail_outplacement_report/reports/welcome_letter_report.xml
  mail_outplacement_report/static/description/email.PNG
  mail_outplacement_report/static/description/icon.png
  mail_outplacement_report/static/description/index.html
Labels: Prio 1

#8 mail_outplacement_report - 12.0-AFC-1139 - Välj mall - Skapa mallar f…
  mail_outplacement_report/__init__.py
  mail_outplacement_report/__manifest__.py
  mail_outplacement_report/data/assigned_coach_data.xml
  mail_outplacement_report/models/__init__.py
  mail_outplacement_report/models/employee.py
  mail_outplacement_report/reports/assigned_coach_report.xml
  mail_outplacement_report/views/employee_view.xml
Labels: Prio 2
